clc
clear
Chewie_right_CO_params = struct( ...
    'monkey_name','Chewie', ...
    'array_name','M1', ...
    'task_name','CO', ...
    'ran_by','MP', ...
    'lab',3, ...
    'bin_width',0.01, ...
    'sorted',0);
% Chewie right M1
base_dir = 'Z:\limblab\lab_folder\Projects\darpa\Chewie_right\nev\';
file_name = 'Chewie_M1_CO_FF_BL_07032015_001';
map_dir = 'Z:\limblab\lab_folder\Projects\darpa\array_map_files\Chewie_right_M1\';
map_name = 'Chewie_Right_M1_SN_1025-0394.cmp';
xds = raw_to_xds(base_dir, file_name, map_dir, map_name, Chewie_right_CO_params);
%save('d.mat','xds');
%%